default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV["host_postgres"] %>
  port: <%= ENV["port_postgres"] %>
  username: <%= ENV["username_postgres"] %>
  password: <%= ENV["password_postgres"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: apiClient_development

test:
  <<: *default
  database: apiClient_test

production:
  <<: *default
  database: apiClient_production
  username: apiClient
  password: <%= ENV["APICLIENT_DATABASE_PASSWORD"] %>
